server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/app_clinic
    username: postgres
#    username: clinic
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  sql:
    init:
      mode: never

jwt:
  secret-key: secretKeyForEnterToCabinet
  expire-time-access: 86_400_000
  expire-time-refresh: 31_104_000_000

SSHSERVER_USERNAME: muhammad
SSHSERVER_PASSWORD: 8fy64us6
SSHSERVER_HOST: 176.96.243.46
SSHSERVER_PORT: 22
DESTINATION_BASE_DIR: /var/www/clinic.m-muhammad.uz/files
DESTINATION_IMAGE: image
DESTINATION_FILE: file

FILE_PATH: http://clinic.m-muhammad.uz/files/